version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha

    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Setup environment keys
          command: bash scripts/cp-env-to-properties.sh
      - run:
          name: Instal Dependencies
          command: bash scripts/install-dependencies.sh
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && - mksdcard -l e 128M mysdcard.img && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on -sdcard mysdcard.img
          background: true

      - run:
          name: Run Tests
          command: ./gradlew spoonDebugAndroidTest -PdisablePreDex --stacktrace --console=plain

      - store_artifacts:
          path: app/build/outputs
      - store_artifacts:
          path: app/build/spoon
      - store_artifacts:
          path: app/build/reports
          destination: reports